name: rmc_customer
description: A new Flutter project.

publish_to: 'none'
version: 1.0.5+5

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  awesome_dialog: ^3.0.1
  flutter_spinkit: ^5.1.0
  lottie: ^2.2.0
  http: ^0.13.5
  dio: ^4.0.6
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  connectivity_plus: ^3.0.2
  pin_code_fields: ^7.4.0
  shared_preferences: ^2.0.15
  share_plus: ^7.1.0
  upgrader: ^8.1.0
  double_back_to_close: ^2.0.0
  validators: ^3.0.0
  flutter_html: ^3.0.0-alpha.5
  onesignal_flutter: ^5.0.4
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  path: ^1.8.2
  file_picker: ^5.0.1
  geolocator: ^9.0.2
  clipboard: ^0.1.3
  otp_autofill: ^2.1.0
  youtube_player_iframe: ^4.0.4
  webview_flutter: ^4.2.0
  agora_rtc_engine: ^6.2.6
  flutter_incoming_call: ^0.1.1
  flutter_ringtone_player: ^3.2.0
  permission_handler: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  package_info_plus: ^4.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.png"
  #flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#FBFCFE"
  image: assets/splash.png
  android: true
  ios: true
#  android_12:
#    color: "#FFFFFF"
#    image: assets/splash2.png
  #flutter pub run flutter_native_splash:create

flutter:
  fonts:
    - family: Regular
      fonts:
        - asset: fonts/poppins_regular.ttf
    - family: Medium
      fonts:
        - asset: fonts/poppins_medium.ttf
    - family: Bold
      fonts:
        - asset: fonts/poppins_semi_bold.ttf
          weight: 500
  uses-material-design: true
  generate: true
  assets:
    - assets/